/**********************************************************************
 *
 * Copyright (c) 2004 Olaf Willuhn
 * All rights reserved.
 *
 * This software is copyrighted work licensed under the terms of the
 * Jameica License.  Please consult the file "LICENSE" for details.
 *
 **********************************************************************/

package de.willuhn.jameica.hbci.server;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.Serializable;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.xml.XMLConstants;
import javax.xml.parsers.DocumentBuilderFactory;

import org.w3c.dom.Element;
import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import de.willuhn.jameica.reminder.Reminder;
import de.willuhn.jameica.reminder.ReminderInterval;
import de.willuhn.jameica.reminder.ReminderInterval.TimeUnit;

/**
 * Data-only reader for the XML produced by {@link java.beans.XMLEncoder}
 * for {@link Reminder} instances.
 */
final class ReminderXmlDecoder
{
  private static final String REMINDER = Reminder.class.getName();
  private static final String INTERVAL = ReminderInterval.class.getName();
  private static final String TIME_UNIT = TimeUnit.class.getName();

  /**
   * No instances.
   */
  private ReminderXmlDecoder()
  {
  }

  /**
   * Decodes a reminder without invoking constructors or methods selected by XML input.
   * @param xml XML generated by {@link java.beans.XMLEncoder}.
   * @return decoded reminder.
   * @throws Exception if the document is malformed or contains unsupported data.
   */
  static Reminder decode(String xml) throws Exception
  {
    DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
    factory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING,true);
    factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl",true);
    factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD,"");
    factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_SCHEMA,"");
    factory.setExpandEntityReferences(false);
    factory.setXIncludeAware(false);

    Element root = factory.newDocumentBuilder()
        .parse(new ByteArrayInputStream(xml.getBytes(StandardCharsets.UTF_8)))
        .getDocumentElement();
    requireName(root,"java");
    requireAttributes(root,"version","class");
    requireAttribute(root,"class","java.beans.XMLDecoder");

    Element object = onlyChild(root);
    requireName(object,"object");
    requireAttributes(object,"class","id");
    requireAttribute(object,"class",REMINDER);
    return parseReminder(object);
  }

  private static Reminder parseReminder(Element object) throws Exception
  {
    Reminder reminder = new Reminder();
    Map<String,Serializable> data = new HashMap<String,Serializable>();
    Map<String,Date> dates = new HashMap<String,Date>();
    Set<String> properties = new HashSet<String>();
    String dataId = null;
    boolean dataReference = false;

    for (Element property:children(object))
    {
      requireName(property,"void");
      String name = requiredAttribute(property,"property");

      if ("data".equals(name))
      {
        if (property.hasAttribute("id"))
        {
          requireAttributes(property,"property","id");
          if (dataId != null)
            throw invalid("duplicate data definition");
          dataId = requiredAttribute(property,"id");
          parseData(property,data,dates);
        }
        else
        {
          requireAttributes(property,"property");
          if (dataReference)
            throw invalid("duplicate data reference");
          Element reference = onlyChild(property);
          requireName(reference,"object");
          requireAttributes(reference,"idref");
          if (dataId == null || !dataId.equals(requiredAttribute(reference,"idref")))
            throw invalid("invalid data reference");
          dataReference = true;
        }
        continue;
      }

      requireAttributes(property,"property");
      if (!properties.add(name))
        throw invalid("duplicate property: " + name);

      Element value = onlyChild(property);
      if ("queue".equals(name))
        reminder.setQueue(parseString(value));
      else if ("date".equals(name))
        reminder.setDate(parseDate(value,dates));
      else if ("end".equals(name))
        reminder.setEnd(parseNullableDate(value,dates));
      else if ("reminderInterval".equals(name))
        reminder.setReminderInterval(parseNullableInterval(value));
      else
        throw invalid("unsupported reminder property: " + name);
    }

    if (dataId != null && !dataReference)
      throw invalid("missing data reference");
    reminder.setData(data);
    return reminder;
  }

  private static void parseData(Element definition, Map<String,Serializable> data, Map<String,Date> dates) throws Exception
  {
    for (Element entry:children(definition))
    {
      requireName(entry,"void");
      requireAttributes(entry,"method");
      requireAttribute(entry,"method","put");
      List<Element> values = children(entry);
      if (values.size() != 2)
        throw invalid("invalid reminder data entry");
      data.put(parseString(values.get(0)),parseValue(values.get(1),dates));
    }
  }

  private static Serializable parseValue(Element value, Map<String,Date> dates) throws Exception
  {
    String name = value.getTagName();
    if ("null".equals(name))
    {
      requireAttributes(value);
      requireNoChildren(value);
      return null;
    }
    if ("string".equals(name))
      return parseString(value);
    if ("boolean".equals(name))
      return Boolean.valueOf(parseText(value));
    if ("byte".equals(name))
      return Byte.valueOf(parseText(value));
    if ("short".equals(name))
      return Short.valueOf(parseText(value));
    if ("int".equals(name))
      return Integer.valueOf(parseText(value));
    if ("long".equals(name))
      return Long.valueOf(parseText(value));
    if ("float".equals(name))
      return Float.valueOf(parseText(value));
    if ("double".equals(name))
      return Double.valueOf(parseText(value));
    if ("object".equals(name))
      return parseDate(value,dates);
    throw invalid("unsupported reminder data type: " + name);
  }

  private static Date parseNullableDate(Element value, Map<String,Date> dates) throws Exception
  {
    if ("null".equals(value.getTagName()))
    {
      requireAttributes(value);
      requireNoChildren(value);
      return null;
    }
    return parseDate(value,dates);
  }

  private static Date parseDate(Element value, Map<String,Date> dates) throws Exception
  {
    requireName(value,"object");
    if (value.hasAttribute("idref"))
    {
      requireAttributes(value,"idref");
      requireNoChildren(value);
      Date date = dates.get(requiredAttribute(value,"idref"));
      if (date == null)
        throw invalid("invalid date reference");
      return date;
    }

    requireAttributes(value,"class","id");
    requireAttribute(value,"class",Date.class.getName());
    Element timestamp = onlyChild(value);
    requireName(timestamp,"long");
    Date date = new Date(Long.parseLong(parseText(timestamp)));
    if (value.hasAttribute("id") && dates.put(requiredAttribute(value,"id"),date) != null)
      throw invalid("duplicate date definition");
    return date;
  }

  private static ReminderInterval parseNullableInterval(Element value) throws Exception
  {
    if ("null".equals(value.getTagName()))
    {
      requireAttributes(value);
      requireNoChildren(value);
      return null;
    }

    requireName(value,"object");
    requireAttributes(value,"class","id");
    requireAttribute(value,"class",INTERVAL);
    ReminderInterval interval = new ReminderInterval();
    Set<String> properties = new HashSet<String>();
    for (Element property:children(value))
    {
      requireName(property,"void");
      requireAttributes(property,"property");
      String name = requiredAttribute(property,"property");
      if (!properties.add(name))
        throw invalid("duplicate interval property: " + name);

      Element child = onlyChild(property);
      if ("interval".equals(name))
      {
        requireName(child,"int");
        interval.setInterval(Integer.parseInt(parseText(child)));
      }
      else if ("timeUnit".equals(name))
        interval.setTimeUnit(parseTimeUnit(child));
      else
        throw invalid("unsupported interval property: " + name);
    }
    return interval;
  }

  private static TimeUnit parseTimeUnit(Element value) throws Exception
  {
    requireName(value,"object");
    requireAttributes(value,"class","method");
    requireAttribute(value,"class",Enum.class.getName());
    requireAttribute(value,"method","valueOf");
    List<Element> values = children(value);
    if (values.size() != 2)
      throw invalid("invalid time unit");
    Element type = values.get(0);
    requireName(type,"class");
    if (!TIME_UNIT.equals(parseText(type)))
      throw invalid("invalid time unit type");
    return TimeUnit.valueOf(parseString(values.get(1)));
  }

  private static String parseString(Element value) throws IOException
  {
    requireName(value,"string");
    return parseText(value);
  }

  private static String parseText(Element value) throws IOException
  {
    requireAttributes(value);
    requireNoChildren(value);
    return value.getTextContent();
  }

  private static Element onlyChild(Element parent) throws IOException
  {
    List<Element> children = children(parent);
    if (children.size() != 1)
      throw invalid("expected one child in " + parent.getTagName());
    return children.get(0);
  }

  private static void requireNoChildren(Element parent) throws IOException
  {
    if (!children(parent).isEmpty())
      throw invalid("unexpected child in " + parent.getTagName());
  }

  private static List<Element> children(Element parent) throws IOException
  {
    List<Element> result = new ArrayList<Element>();
    NodeList nodes = parent.getChildNodes();
    for (int i=0;i<nodes.getLength();++i)
    {
      Node node = nodes.item(i);
      if (node instanceof Element)
        result.add((Element)node);
      else if (node.getNodeType() == Node.TEXT_NODE || node.getNodeType() == Node.CDATA_SECTION_NODE)
        continue;
      else if (node.getNodeType() != Node.COMMENT_NODE)
        throw invalid("unexpected XML content");
    }
    return result;
  }

  private static void requireName(Element element, String name) throws IOException
  {
    if (!name.equals(element.getTagName()))
      throw invalid("expected " + name + ", got " + element.getTagName());
  }

  private static void requireAttributes(Element element, String... allowed) throws IOException
  {
    Set<String> names = new HashSet<String>();
    for (String name:allowed)
      names.add(name);
    NamedNodeMap attributes = element.getAttributes();
    for (int i=0;i<attributes.getLength();++i)
    {
      String name = attributes.item(i).getNodeName();
      if (!names.contains(name))
        throw invalid("unsupported attribute: " + name);
    }
  }

  private static String requiredAttribute(Element element, String name) throws IOException
  {
    if (!element.hasAttribute(name))
      throw invalid("missing attribute: " + name);
    return element.getAttribute(name);
  }

  private static void requireAttribute(Element element, String name, String value) throws IOException
  {
    if (!value.equals(requiredAttribute(element,name)))
      throw invalid("invalid " + name + " attribute");
  }

  private static IOException invalid(String message)
  {
    return new IOException("invalid reminder XML: " + message);
  }
}
