# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    paths:
      - '**.java'
      - '**.gradle'
  pull_request:
    paths:
      - '**.java'
      - '**.gradle'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download primary repository
      uses: actions/checkout@v2
      with:
        repository: 'ruderphilipp/jmc'
        submodules: recursive
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Checkout current commit
      # see <https://stackoverflow.com/q/63795736>
      working-directory: ./hibiscus
      run: |
        # fetch heads for push actions
        git fetch --force ${{ github.event.repository.git_url }} "+refs/heads/*:refs/remotes/origin/*"
        # fetch heads for pull requests
        git fetch --force ${{ github.event.repository.git_url }} "+refs/pull/*/head:refs/remotes/origin/pr/*"
        git checkout ${{ github.sha }} || git checkout ${{ github.event.pull_request.head.sha }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build test
